import { Community, Event, User, Attendee, Notification, EventRating, WaitlistEntry } from '../types';

export const MOCK_COMMUNITIES: Community[] = [
  {
    id: 'c1',
    name: 'IEEE Öğrenci Topluluğu',
    shortName: 'IEEE',
    description: 'Elektrik-Elektronik Mühendisleri Enstitüsü öğrenci kolu olarak teknoloji ve mühendislik alanında etkinlikler düzenliyoruz.',
    memberCount: 342,
    eventCount: 47,
    category: 'technology',
    university: 'İstanbul Teknik Üniversitesi',
    foundedAt: '2018-09-01',
  },
  {
    id: 'c2',
    name: 'Müzik Kulübü',
    shortName: 'MÜZİK',
    description: 'Üniversitemizin köklü müzik topluluğu olarak konserler, atölyeler ve müzik eğitimi etkinlikleri düzenliyoruz.',
    memberCount: 218,
    eventCount: 31,
    category: 'music',
    university: 'İstanbul Teknik Üniversitesi',
    foundedAt: '2015-03-15',
  },
  {
    id: 'c3',
    name: 'Girişimcilik Kulübü',
    shortName: 'GİRİŞİM',
    description: 'Startup ekosistemi ve girişimcilik kültürünü geliştirmek için hackathonlar, mentorluk programları düzenliyoruz.',
    memberCount: 156,
    eventCount: 23,
    category: 'technology',
    university: 'İstanbul Teknik Üniversitesi',
    foundedAt: '2019-10-01',
  },
];

export const MOCK_USERS: User[] = [
  {
    id: 'u1',
    name: 'Ahmet Yılmaz',
    email: 'ahmet.yilmaz@itu.edu.tr',
    studentId: '150180001',
    role: 'admin',
    communityId: 'c1',
    joinedAt: '2023-09-15',
    eventsAttended: 18,
    eventsRegistered: ['e1', 'e2', 'e3'],
    avatar: undefined,
  },
  {
    id: 'u2',
    name: 'Zeynep Kaya',
    email: 'zeynep.kaya@itu.edu.tr',
    studentId: '150190042',
    role: 'organizer',
    communityId: 'c1',
    joinedAt: '2023-09-20',
    eventsAttended: 12,
    eventsRegistered: ['e1', 'e3'],
    avatar: undefined,
  },
];

const now = new Date();
const addDays = (days: number) => new Date(now.getTime() + days * 86400000).toISOString().split('T')[0];
const subtractDays = (days: number) => new Date(now.getTime() - days * 86400000).toISOString().split('T')[0];

export const MOCK_EVENTS: Event[] = [
  {
    id: 'e1',
    title: 'Web3 & Blockchain Atölyesi',
    description: 'Blok zinciri teknolojisinin temellerini ve Web3 ekosistemini keşfedelim. Pratik örneklerle Solidity programlama diline giriş yapacağız. Katılımcılar kendi akıllı sözleşmelerini yazacak ve test ağında deploy edecekler.',
    communityId: 'c1',
    communityName: 'IEEE Öğrenci Topluluğu',
    organizerId: 'u1',
    category: 'workshop',
    date: addDays(3),
    startTime: '14:00',
    endTime: '17:00',
    location: 'Taşkışla Binası A-101',
    locationDetail: 'İTÜ Taşkışla Kampüsü, Zemin Kat',
    maxCapacity: 50,
    registeredCount: 50,
    checkedInCount: 0,
    status: 'upcoming',
    tags: ['blockchain', 'web3', 'solidity', 'ethereum'],
    isRegistrationOpen: true,
    qrCodeData: 'EVENT:e1:IEEE:Web3Blockchain2024',
    createdAt: subtractDays(7),
    interestedCount: 67,
    waitlistCount: 12,
    agenda: [
      { id: 'a1', time: '14:00', title: 'Açılış & Tanışma', duration: 15 },
      { id: 'a2', time: '14:15', title: 'Blockchain Temelleri', speaker: 'Ahmet Yılmaz', duration: 45 },
      { id: 'a3', time: '15:00', title: 'Solidity ile Akıllı Sözleşme', speaker: 'Dr. Kemal Çelik', duration: 60 },
      { id: 'a4', time: '16:00', title: 'Pratik: Deploy Atölyesi', duration: 45 },
      { id: 'a5', time: '16:45', title: 'Soru & Cevap', duration: 15 },
    ],
  },
  {
    id: 'e2',
    title: 'Bahar Konseri 2024',
    description: 'Üniversitemiz müzik kulübünün yıllık bahar konseri! Klasik ve çağdaş eserlerden oluşan zengin bir repertuarla sizlerle buluşuyoruz. Yerli ve yabancı sanatçıların katılımıyla unutulmaz bir gece sizi bekliyor.',
    communityId: 'c2',
    communityName: 'Müzik Kulübü',
    organizerId: 'u2',
    category: 'social',
    date: addDays(7),
    startTime: '19:30',
    endTime: '22:00',
    location: 'Kültür Merkezi Büyük Salon',
    locationDetail: 'İTÜ Kültür Merkezi, 1. Kat',
    maxCapacity: 300,
    registeredCount: 247,
    checkedInCount: 0,
    status: 'upcoming',
    tags: ['müzik', 'konser', 'bahar', 'canlı performans'],
    isRegistrationOpen: true,
    qrCodeData: 'EVENT:e2:MUZIK:BaharKonseri2024',
    createdAt: subtractDays(14),
    interestedCount: 312,
  },
  {
    id: 'e3',
    title: 'Startup Hackathon 2024',
    description: '48 saatlik yoğun bir girişimcilik maratonuna hazır mısınız? Ekibinizle gerçek problemlere yenilikçi çözümler geliştirin. Kazananlara mentorluk programı ve toplam 50.000 TL ödül havuzu!',
    communityId: 'c3',
    communityName: 'Girişimcilik Kulübü',
    organizerId: 'u1',
    category: 'competition',
    date: addDays(14),
    startTime: '09:00',
    endTime: '09:00',
    location: 'Mühendislik Fakültesi',
    locationDetail: 'İTÜ Ayazağa Kampüsü, Mühendislik Binası',
    maxCapacity: 100,
    registeredCount: 78,
    checkedInCount: 0,
    status: 'upcoming',
    tags: ['hackathon', 'startup', 'girişimcilik', 'ödül'],
    isRegistrationOpen: true,
    qrCodeData: 'EVENT:e3:GIRISIM:Hackathon2024',
    createdAt: subtractDays(10),
    interestedCount: 142,
    agenda: [
      { id: 'b1', time: '09:00', title: 'Açılış Töreni & Kurallar', duration: 30 },
      { id: 'b2', time: '09:30', title: 'Takım Oluşturma', duration: 30 },
      { id: 'b3', time: '10:00', title: 'Geliştirme Maratonu Başlıyor', duration: 480 },
      { id: 'b4', time: '18:00', title: '1. Gün Check-in & Mentörlük', duration: 60 },
      { id: 'b5', time: '09:00', title: '2. Gün: Son Sprint', speaker: '2. Gün', duration: 360 },
      { id: 'b6', time: '15:00', title: 'Sunum & Demo Day', duration: 120 },
      { id: 'b7', time: '17:00', title: 'Ödül Töreni', duration: 60 },
    ],
  },
  {
    id: 'e4',
    title: 'Python ile Yapay Zeka Semineri',
    description: 'Makine öğrenmesi ve derin öğrenme algoritmalarını Python ile uygulamalı olarak öğrenin. TensorFlow ve PyTorch frameworkleri üzerinde çalışarak gerçek veri setleriyle modeller eğiteceksiniz.',
    communityId: 'c1',
    communityName: 'IEEE Öğrenci Topluluğu',
    organizerId: 'u1',
    category: 'seminar',
    date: subtractDays(3),
    startTime: '15:00',
    endTime: '18:00',
    location: 'Taşkışla Binası B-201',
    maxCapacity: 60,
    registeredCount: 58,
    checkedInCount: 52,
    status: 'completed',
    tags: ['python', 'yapay zeka', 'makine öğrenmesi', 'tensorflow'],
    isRegistrationOpen: false,
    qrCodeData: 'EVENT:e4:IEEE:PythonAI2024',
    createdAt: subtractDays(17),
    interestedCount: 89,
    averageRating: 4.6,
    ratingCount: 41,
  },
  {
    id: 'e5',
    title: 'Kariyer Günleri & Networking',
    description: 'Sektörün önde gelen şirketlerinin katılımıyla gerçekleşecek kariyer fuarında staj ve iş fırsatlarını keşfedin. CV değerlendirme, mülakat simülasyonu ve networking etkinlikleri.',
    communityId: 'c1',
    communityName: 'IEEE Öğrenci Topluluğu',
    organizerId: 'u2',
    category: 'meetup',
    date: subtractDays(10),
    startTime: '10:00',
    endTime: '17:00',
    location: 'Spor Salonu',
    maxCapacity: 500,
    registeredCount: 423,
    checkedInCount: 387,
    status: 'completed',
    tags: ['kariyer', 'networking', 'staj', 'iş fırsatı'],
    isRegistrationOpen: false,
    qrCodeData: 'EVENT:e5:IEEE:KariyerGunleri2024',
    createdAt: subtractDays(30),
    interestedCount: 501,
    averageRating: 4.8,
    ratingCount: 203,
  },
  {
    id: 'e6',
    title: 'Doğa Yürüyüşü & Kamp',
    description: 'Haftasonu kaçamağı! Belgrad Ormanları\'nda grup yürüyüşü ve kamp gecesi. Ekipman listesi ve ulaşım detayları kayıt sonrası paylaşılacaktır.',
    communityId: 'c2',
    communityName: 'Müzik Kulübü',
    organizerId: 'u2',
    category: 'trip',
    date: addDays(21),
    startTime: '08:00',
    endTime: '20:00',
    location: 'Belgrad Ormanları',
    maxCapacity: 30,
    registeredCount: 28,
    checkedInCount: 0,
    status: 'upcoming',
    tags: ['doğa', 'yürüyüş', 'kamp', 'haftasonu'],
    isRegistrationOpen: false,
    qrCodeData: 'EVENT:e6:MUZIK:DogaYuruyusu2024',
    createdAt: subtractDays(5),
    interestedCount: 55,
  },
];

export const MOCK_ATTENDEES: Attendee[] = [
  { id: 'a1', userId: 'u1', eventId: 'e1', name: 'Ahmet Yılmaz', studentId: '150180001', registeredAt: subtractDays(5), checkedIn: false },
  { id: 'a2', userId: 'u2', eventId: 'e1', name: 'Zeynep Kaya', studentId: '150190042', registeredAt: subtractDays(4), checkedIn: false },
  { id: 'a3', userId: 'u3', eventId: 'e1', name: 'Mehmet Demir', studentId: '150200078', registeredAt: subtractDays(3), checkedIn: false },
  { id: 'a4', userId: 'u4', eventId: 'e1', name: 'Ayşe Çelik', studentId: '150210095', registeredAt: subtractDays(2), checkedIn: false },
  { id: 'a5', userId: 'u5', eventId: 'e1', name: 'Mustafa Şahin', studentId: '150180023', registeredAt: subtractDays(1), checkedIn: false },
  { id: 'a6', userId: 'u4', eventId: 'e4', name: 'Ayşe Çelik', studentId: '150210095', registeredAt: subtractDays(15), checkedIn: true, checkedInAt: subtractDays(3) + 'T15:12:00Z' },
  { id: 'a7', userId: 'u5', eventId: 'e4', name: 'Mustafa Şahin', studentId: '150180023', registeredAt: subtractDays(14), checkedIn: true, checkedInAt: subtractDays(3) + 'T15:08:00Z' },
  { id: 'a8', userId: 'u1', eventId: 'e4', name: 'Ahmet Yılmaz', studentId: '150180001', registeredAt: subtractDays(16), checkedIn: true, checkedInAt: subtractDays(3) + 'T15:05:00Z' },
];

export const MOCK_WAITLIST: WaitlistEntry[] = [
  { id: 'w1', eventId: 'e1', userId: 'u10', name: 'Berk Arslan', studentId: '150220011', joinedAt: subtractDays(1) },
  { id: 'w2', eventId: 'e1', userId: 'u11', name: 'Elif Yıldız', studentId: '150220034', joinedAt: subtractDays(1) },
];

export const MOCK_RATINGS: EventRating[] = [
  { id: 'r1', eventId: 'e4', userId: 'u3', rating: 5, comment: 'Harika bir etkinlikti! Çok şey öğrendim.', createdAt: subtractDays(2) },
  { id: 'r2', eventId: 'e4', userId: 'u4', rating: 4, comment: 'Güzel organizasyon, içerik çok iyiydi.', createdAt: subtractDays(2) },
  { id: 'r3', eventId: 'e5', userId: 'u1', rating: 5, comment: 'Kariyer fırsatları açısından çok verimli geçti.', createdAt: subtractDays(9) },
];

export const MOCK_NOTIFICATIONS: Notification[] = [
  {
    id: 'n1',
    userId: 'u1',
    title: 'Etkinlik Yaklaşıyor!',
    body: 'Web3 & Blockchain Atölyesi\'ne 3 gün kaldı. Hazır olun!',
    type: 'event_reminder',
    eventId: 'e1',
    read: false,
    createdAt: new Date(Date.now() - 2 * 3600000).toISOString(),
  },
  {
    id: 'n2',
    userId: 'u1',
    title: 'Yeni Etkinlik Duyurusu',
    body: 'Startup Hackathon 2024 kayıtları açıldı! Hemen kaydol.',
    type: 'event_created',
    eventId: 'e3',
    read: false,
    createdAt: new Date(Date.now() - 5 * 3600000).toISOString(),
  },
  {
    id: 'n3',
    userId: 'u1',
    title: 'Giriş Başarılı',
    body: 'Python ile Yapay Zeka Semineri\'ne girişiniz onaylandı.',
    type: 'check_in_success',
    eventId: 'e4',
    read: true,
    createdAt: new Date(Date.now() - 3 * 86400000).toISOString(),
  },
  {
    id: 'n4',
    userId: 'u1',
    title: 'Kariyer Günleri Güncellendi',
    body: 'Kariyer Günleri etkinliği için 5 yeni şirket daha katılıyor!',
    type: 'event_updated',
    eventId: 'e5',
    read: true,
    createdAt: new Date(Date.now() - 11 * 86400000).toISOString(),
  },
  {
    id: 'n5',
    userId: 'u1',
    title: 'Topluluk Duyurusu',
    body: 'IEEE yıllık olağan genel kurul toplantısı 15 Haziran\'da yapılacak.',
    type: 'general',
    read: true,
    createdAt: new Date(Date.now() - 15 * 86400000).toISOString(),
  },
];
